const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why can't you give Elsa a balloon? Because she will let it go!",
    "Why did the bicycle fall over? It was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I would tell you a construction pun, but I'm still working on it.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why was the math book sad? It had too many problems.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
    "What do you call a fish wearing a crown? A king fish.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why did the coffee file a police report? It got mugged.",
    "Why don't programmers like nature? It has too many bugs.",
    "How does a penguin build its house? Igloos it together.",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What do you call an alligator in a vest? An investigator.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why don’t oysters share their pearls? Because they are shellfish.",
    "Why are ghosts bad at lying? Because they are too transparent.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What’s a skeleton’s least favorite room? The living room.",
    "How do you organize a space party? You planet.",
    "Why did the picture go to jail? It was framed.",
    "Why can't you trust stairs? They're always up to something.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "What kind of music do mummies listen to? Wrap music.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why did the man put his money in the blender? He wanted to make some liquid assets.",
    "How does a cucumber become a pickle? It goes through a jarring experience.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "Why can't a leopard hide? Because he's always spotted.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "How many tickles does it take to make an octopus laugh? Ten-tickles.",
    "Why did the cookie go to the doctor? It was feeling crummy.",
    "Why can't you trust an atom? Because they make up everything.",
    "Why did the frog take the bus to work? His car got toad away.",
    "Why are frogs so happy? They eat whatever bugs them.",
    "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    "What did one plate say to the other? Lunch is on me.",
    "What’s brown and sticky? A stick.",
    "How do you organize a fantastic party? You planet.",
    "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "Why did the boy bring a ladder to school? He wanted to go to high school.",
    "Why did the stadium get hot? Because all the fans left.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the bicycle stand up by itself? It was two-tired.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the grape stop in the middle of the road? It ran out of juice.",
    "What did the fisherman say to the magician? Pick a cod, any cod.",
    "What’s a vampire’s favorite fruit? A blood orange.",
    "How do you fix a broken tomato? With tomato paste.",
    "Why did the hipster burn his mouth? He drank the coffee before it was cool.",
    "What do you call a group of musical whales? An orca-stra.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why do trees seem suspicious on sunny days? They’re always a little shady.",
    "Why are elevator jokes so good? They work on so many levels.",
    "Why don’t koalas count as bears? They don’t have the right koalafications.",
    "How do you find Will Smith in the snow? You look for fresh prints.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "What do you call a boomerang that doesn’t come back? A stick.",
    "Why don’t bananas ever get lonely? They hang out in bunches.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "Why can’t a nose be 12 inches long? Because then it would be a foot!",
    "What do you call a shoe made out of a banana? A slipper.",
    "Why did the fish blush? Because it saw the ocean’s bottom.",
    "What happens to a frog’s car when it breaks down? It gets toad away.",
    "Why was the broom late to the meeting? It swept in last minute.",
    "Why do ducks have feathers? To cover their butt quacks.",
    "What’s black and white and goes around and around? A penguin in a revolving door.",
    "How do you make holy water? You boil the hell out of it.",
    "Why did the golfer bring extra pants? In case he got a hole in one.",
    "How do cows stay up to date? They read the moos-paper.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "How does a hurricane see? With its eye.",
    "What’s a robot’s favorite music? Heavy metal.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they’d be bagels.",
    "Why don’t vampires attack Taylor Swift? Because she has bad blood.",
    "How do you make a lemon drop? Just let it fall.",
    "What do you call an illegally parked frog? Toad.",
    "Why did the scarecrow become a successful politician? Because he was outstanding in his field.",
    "Why did the rabbit go to the barber? To get a harecut.",
    "What do you get when you cross a snowman and a vampire? Frostbite."
];

// Function to display a random joke
function displayRandomJoke() {
    const randomIndex = Math.floor(Math.random() * jokes.length);
    const jokeDisplay = document.getElementById("jokeDisplay");
    jokeDisplay.innerHTML = jokes[randomIndex];
}

// Display the first joke when the page loads
window.onload = displayRandomJoke;

// Add event listener to the button for generating a new joke
const jokeButton = document.getElementById("jokeButton");
jokeButton.addEventListener("click", displayRandomJoke);